plugins {
    id 'com.android.application' version '8.8.2' apply false
    id 'com.android.library' version '8.8.2' apply false
    id 'com.chaquo.python' version '15.0.1' apply false
    id 'org.jetbrains.kotlin.android' version '2.0.20'  apply false 
    id 'org.jetbrains.kotlin.plugin.compose' version '2.0.20'  apply false 
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}

project.ext {
    gsonVersion = '2.13.1'
    media3Version = '1.8.0'
    okhttpVersion = '5.1.0'
}
