plugins {
    id 'com.android.application' version '8.8.0-alpha05' apply false
    id 'com.android.library' version '8.8.0-alpha05' apply false
    id 'com.chaquo.python' version '15.0.1' apply false
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}

project.ext {
    gsonVersion = '2.11.0'
    media3Version = '1.6.1'
    okhttpVersion = '5.0.0-alpha.14'
}
