pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        jcenter()
        google()
        maven { url "https://jitpack.io" }
        maven {
            url "http://4thline.org/m2"
            allowInsecureProtocol = true
        }
        maven { url "https://chaquo.com/maven" }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        jcenter()
        google()
        flatDir { dirs "$rootDir/app/libs" }
        maven { url "https://jitpack.io" }
        maven {
            url "http://4thline.org/m2"
            allowInsecureProtocol = true
        }
        maven { url "https://chaquo.com/maven" }
    }
}
include ':app'
include ':catvod'
include ':chaquo'
include ':quickjs'
rootProject.name = "TV"
