[versions]
agp = "9.4.0"
python = "17.0.0"
minSdk = "24"
targetSdk = "37"
compileSdk = "37"

annotation = "1.10.0"
appcompat = "1.8.0"
biometric = "1.1.0"
desugar = "2.1.5"
leanback = "1.2.0"
lifecycleService = "2.11.0"
media = "1.8.0"
palette = "1.0.0"
preference = "1.2.1"
recyclerview = "1.4.0"
room = "2.8.5"
splashscreen = "1.2.0"
startup = "1.2.0"
swiperefreshlayout = "1.2.0"
viewpager2 = "1.1.0"

androidGifDrawable = "1.2.32"
androidautosize = "1.2.1"
brotli = "0.1.2"
commonsCompress = "1.28.0"
customactivityoncrash = "2.4.0"
flexbox = "3.0.0"
glide = "5.0.9"
greenrobot = "3.3.1"
gson = "2.14.0"
guava = "33.7.1-android"
jna = "5.19.1"
jupnp = "3.0.5"
juniversalchardet = "1.0.3"
logger = "2.2.0"
lottie = "6.7.1"
material = "1.14.0"
materialdesigncolors = "1.0.0"
nanohttpd = "2.3.1"
newpipeextractor = "v0.26.5"
okhttp = "5.5.0"
permissionx = "1.8.1"
quickjs = "3.2.3"
rtmpClient = "v3.2.0.m2"
sardine = "0.9"
simpleXml = "2.7.1"
smbj = "0.15.0"
textdrawable = "1.0.3"
zxingAndroidEmbedded = "4.3.0"
zxingCore = "3.5.4"

[libraries]
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric" }
desugar = { group = "com.android.tools", name = "desugar_jdk_libs_nio", version.ref = "desugar" }
leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanback" }
lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycleService" }
media = { group = "androidx.media", name = "media", version.ref = "media" }
palette = { group = "androidx.palette", name = "palette", version.ref = "palette" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "startup" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }

android-gif-drawable = { group = "pl.droidsonroids.gif", name = "android-gif-drawable", version.ref = "androidGifDrawable" }
androidautosize = { group = "com.github.JessYanCoding", name = "AndroidAutoSize", version.ref = "androidautosize" }
brotli = { group = "org.brotli", name = "dec", version.ref = "brotli" }
commons-compress = { group = "org.apache.commons", name = "commons-compress", version.ref = "commonsCompress" }
customactivityoncrash = { group = "cat.ereza", name = "customactivityoncrash", version.ref = "customactivityoncrash" }
eventbus = { group = "org.greenrobot", name = "eventbus", version.ref = "greenrobot" }
eventbus-annotation-processor = { group = "org.greenrobot", name = "eventbus-annotation-processor", version.ref = "greenrobot" }
flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-annotations = { group = "com.github.bumptech.glide", name = "annotations", version.ref = "glide" }
glide-avif-integration = { group = "com.github.bumptech.glide", name = "avif-integration", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
glide-okhttp3-integration = { group = "com.github.bumptech.glide", name = "okhttp3-integration", version.ref = "glide" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
jna = { group = "net.java.dev.jna", name = "jna", version.ref = "jna" }
juniversalchardet = { group = "com.googlecode.juniversalchardet", name = "juniversalchardet", version.ref = "juniversalchardet" }
rtmp-client = { group = "com.github.mcxinyu", name = "LibRtmp-Client-for-Android", version.ref = "rtmpClient" }
logger = { group = "com.orhanobut", name = "logger", version.ref = "logger" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
materialdesigncolors = { group = "com.github.bassaer", name = "materialdesigncolors", version.ref = "materialdesigncolors" }
nanohttpd = { group = "org.nanohttpd", name = "nanohttpd", version.ref = "nanohttpd" }
newpipeextractor = { group = "com.github.TeamNewPipe", name = "NewPipeExtractor", version.ref = "newpipeextractor" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-dnsoverhttps = { group = "com.squareup.okhttp3", name = "okhttp-dnsoverhttps", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
org-jupnp = { group = "org.jupnp", name = "org.jupnp", version.ref = "jupnp" }
org-jupnp-android = { group = "org.jupnp", name = "org.jupnp.android", version.ref = "jupnp" }
org-jupnp-support = { group = "org.jupnp", name = "org.jupnp.support", version.ref = "jupnp" }
permissionx = { group = "com.guolindev.permissionx", name = "permissionx", version.ref = "permissionx" }
quickjs-android = { group = "wang.harlon.quickjs", name = "wrapper-android", version.ref = "quickjs" }
quickjs-java = { group = "wang.harlon.quickjs", name = "wrapper-java", version.ref = "quickjs" }
sardine = { group = "com.github.thegrizzlylabs", name = "sardine-android", version.ref = "sardine" }
simple-xml = { group = "org.simpleframework", name = "simple-xml", version.ref = "simpleXml" }
smbj = { group = "com.hierynomus", name = "smbj", version.ref = "smbj" }
textdrawable = { group = "com.github.jahirfiquitiva", name = "TextDrawable", version.ref = "textdrawable" }
zxing-android-embedded = { group = "com.journeyapps", name = "zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxingCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
chaquo-python = { id = "com.chaquo.python", version.ref = "python" }

[bundles]
glide = ["glide", "glide-annotations", "glide-avif-integration", "glide-okhttp3-integration"]
jupnp = ["org-jupnp", "org-jupnp-android", "org-jupnp-support"]
okhttp = ["okhttp", "okhttp-dnsoverhttps", "okhttp-logging-interceptor"]
