plugins {
    alias libs.plugins.android.library
}

android {
    namespace = 'com.fongmi.android.tv.quickjs'

    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        minSdk libs.versions.minSdk.get().toInteger()
        targetSdk libs.versions.targetSdk.get().toInteger()
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        coreLibraryDesugaringEnabled = true
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    implementation project(':catvod')
    implementation libs.quickjs.android
    implementation libs.quickjs.java
    coreLibraryDesugaring libs.desugar
}
