plugins {
    id 'com.android.library'
    id 'com.chaquo.python'
}

android {
    namespace = 'com.fongmi.chaquo'

    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        consumerProguardFiles 'consumer-rules.pro'
        minSdk libs.versions.minSdk.get().toInteger()
        targetSdk libs.versions.targetSdk.get().toInteger()
        ndk { abiFilters "arm64-v8a", "armeabi-v7a" }
        python {
            version = "3.10"
            pip {
                install("-r", "requirements.txt")
            }
        }
    }

    sourceSets {
        main {
            python.srcDirs = ["src/main/python"]
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled = true
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    implementation project(':catvod')
    coreLibraryDesugaring libs.desugar
}
